# Generated by Django 5.0.7 on 2024-11-11 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_transaction_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyincome',
            options={'ordering': ['-month']},
        ),
        migrations.AddField(
            model_name='monthlyincome',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
