# Generated by Django 5.0.7 on 2024-11-14 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_monthlyincome_options_monthlyincome_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyincome',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
